= Cross-Testing Feedback

__Durchführende Gruppe: 06__ +
__Anwendung von Gruppe: 02__

== Getestetes System
Below the Sun Campingplatz

== Fehler-Report
// See http://asciidoctor.org/docs/user-manual/#tables
[options="header"]
|===
|Pfad |Parameter |Beschreibung |Rückgabe
| view_campinglots/{id}|StartDate = nichts, EndDate = nichts |Reservierung ohne Angabe von Anfangs oder End Datum in den Warenkorb zu legen| Whitelabel Error Page
| view_campinglots/{id}|StartDate = heute, EndDate = 2023-12-16 |Reservierung mit heutigem Tag als Anfangs in den Warenkorb zu legen| Whitelabel Error Page
| view_campinglots/{id}|StartDate = 2023-12-15, EndDate = 2023-12-12 |Reservierung mit Anfangs- vor dem Enddatum in den Warenkorb zu legen| Whitelabel Error Page
| view_campinglots/{id}|StartDate = 2023-12-12, EndDate = 2023-12-12 |Reservierung mit gleichem Anfangs- und Enddatum in den Warenkorb zu legen| Whitelabel Error Page
| view_campinglots/{id}|StartDate = 2023-12-13, EndDate = 2023-12-16 und StartDate = 2023-12-13, EndDate = 2023-12-14|Einen Bereich reservieren, der bereits reserviert ist| Whitelabel Error Page
| bookings |paid-amount = NaN|ein Mitarbeiter kann NaN in das Zahlungsbetrag-Feld eintragen| Whitelabel Error Page
|borrow-page|Date = 2023-16-12, StartTime = 15.15, EndTime = 15.15 |Reservierung mit gleicher Anfangs- und Endzeit in den Warenkorb zu legen| Whitelabel Error Page
|change_password|Account: camping_lotte +
 Altes Passwort: abc +
Neues Passwort: 1234 |Beim Passwort ändern, nicht das richtige alte Passwort eingeben| Whitelabel Error Page
|===

== Sonstiges

* Optik der Anwendung
    - Die Empfehlungen auf der Startseite sind eine gute Idee

* Fehlende Features
    - man sollte den Preis eines Platzes pro Tag sehen
    - dem eingeloggten Nutzer fehlt eine Übersicht über seine getätigten Buchungen
    - dem eingeloggten Nutzer fehlt eine Übersicht über seine ausgeliehenen Sportgeräte
    - Bei den Sportgeräten im Dashboard ist es nicht möglich, Sportgeräte zu entfernen (bzw. deren Anzahl zu senken).


* Korrektheit
    - Man kann beliebige Parkplätze auswählen, egal ein Stellplatz diesen besitz oder nicht
    - Unabhängig davon, welcher Parkplatz ausgewählt ist, sind die Parkkosten 2 Euro
   

* Interaktion mit der Anwendung (Usability)
    - nachdem man einen Account erstellt möchte man angemeldet bleiben
    - Feedback bei add-to-cart wäre schön
    - kann man seine eigenen Buchungen sehen?
    - es können in einer Kategorie keine zwei Filter zusammen gesetzt werden, nur jeweil ein Haken möglich
    - zudem können bereits getätigte Haken nicht komplett zurückgenommen werden, nur versetzt
    - Es fehlt die Information über den Preis eines Sportgerät verschiedener Kategorien und auch über die Arbeitszeit, von wann bis wann kann der Kunde sie ausleihen. 

* Rechtschreibfehler
    - Nachricht, wenn im Cart die Zeiträume kollidieren (13tes Wort: istoder)

* Sonstige Fehler
    - (ein und derselbe Stellplatz (sowohl Saisonal als auch normal) kann mehrfach, auch mit dem selben Parkplatz in den Warenkorb gelegt werden)
       -> wirft dann aber einen Fehler beim bestellen

* Dauercamper
 - im Catalog kein Preis sichtbar // das haben wir schon bei fehlende Features
 - Preis im Einkaufswagen ziemlich hoch, S3 kostet 63900 für 2024-04-01 bis 2024-04-02  // dass die daten komisch sind ist doch keine kritikpunkt
 - Preis für Dauercamper wird aktuell pro nacht festgelegt, fände pro Monat besser
 - Die Abrechnung sollte wahlweise pro Monat oder Jahr erfolgen
  - Berechnung der Buchung erfolgt weder jährlich noch monatlich, sondern pro Nacht im Dashboard
  - Abrechnung der Strom- und Wasserkosten fehlt
  - Vorkaufrecht für den Mieter der letzten Saison fehlt, da eine Buchung nach Ablauf der Saison sofort möglich ist für einen anderen Nutzer


== Verbesserungsvorschläge

- Die Mitarbeiter Platz Ansicht ist einfach besser als die Customer Platz ansicht? Die mal Übernehmen?
- Es ist möglich, dass gleiche Objekt mehrmals in den Einkaufwagen zu legen. Auch wenn danach ein Fehler beim Buche kommt, wäre eine frühere Fehlermeldung schön.
- Beim Sportgeräteverleih die grau eingetragenene Zeiten evtl übernehmen, wenn nichts anderes eingegeben wird, so muss nicht immer die vollständige Zeit eingetragen werden
- Für die Überschaubarkeit wäre das Persistieren der Filtereinstellungen nach Absenden des Formulares schön und nicht nur das Anzeigen in der Überschrift.
- etwas komplizierte Eingabe zur Bezahlung einer Buchung, da sowieso nur der richtige Betrag händisch eingegeben werden muss.
- sehr schöner Graph bei den Finanzen, aber es ist nicht genau ersichtlich was der Graph aussagen soll (#Achsenbeschriftung)-
- Beim Sportgeräteverleih, wenn der User nicht eingeloggt ist und dem Button book now klickt, wäre es besser,wenn die Login/Register direkt angezeigt werden, nicht nur die Nachricht.


== Fragen die aufgekommen sind

 - Wenn der Mitarbeiter die Buchung als bezahlt markiert, muss der einen Betrag angeben. Dieser uss aber immer genau den Kosten entsprechen. Wieso muss der das dann noch angeben?
 
