= Zeiterfassung für Gruppe 06

Notieren Sie die Zeit in Minuten für jeden Entwickler und – getrennt davon – für Team-Treffen pro Woche (Wochengranularität).
Die individuell erfasste Zeit beinhaltet auch das Lesen von Dokumentationen, Besprechungen mit Teamkollegen und sonstige auf das Praktikum bezogene Aufgaben, jedoch *nicht* das Team-Treffen (= letzte Spalte).

// See http://asciidoctor.org/docs/user-manual/#tables
[option="headers"]
|===
|Woche |Armin |Vincent |Irina |Richard |Jannes |Daniel | Tom || Meetings
|1     |240   |120     |120   |180     |100    |40     |20   ||40+90
|2     |240   |180     |120   |170     |240    |120    |120  ||90
|3     |180   |360     |220   |200     |160    |360    |120  ||90
|4     |240   |240     |200   |20      |250    |510    |20   ||90
|5     |200   |820     |510   |510     |180    |690    |180  ||90
|6     |420   |240     |…     |140     |250    |690    |120  ||115
|7     |…     |…       |…     |160     |90+... |60     |210  ||90+100
|8     |…     |…       |…     |600     |…      |570    |300  ||90
|9     |…     |…       |…     |…       |…      |…      |…    ||
|10    |…     |…       |…     |…       |…      |…      |…    ||
|11    |…     |…       |…     |…       |…      |…      |…    ||
|12    |…     |…       |…     |…       |…      |…      |…    ||
|===

Bitte tragen Sie am Ende des Praktikums noch folgende weitere Werte ein:
Summe der Arbeitsstunden pro Student:

SUMME(SPALTE(DevX))

Arbeitsstunden pro Woche pro Student:

SUMME(SPALTE(DevX)) / 12

Durchschnittliche Arbeitzeit aller Studenten pro Woche:

(SUMME(SPALTE(Dev1)) + SUMME(SPALTE(Dev2)) + SUMME(SPALTE(Dev3)) + SUMME(SPALTE(Dev4)) + SUMME(SPALTE(Dev5)) +SUMME(SPALTE(Dev6))) / 6
