= Cross-Testing Feedback

__Durchführende Gruppe:__ swt23w02
__Anwendung von Gruppe:__ swt23w06

== Getestetes System
System zur Buchung von Campingplätzen, zur Ausleihung von Sportgeräten und zur Verwaltung des Geschäfts (Stellplätze, Geräte, User, Finanzen, etc.).

== Fehler-Report
// See http://asciidoctor.org/docs/user-manual/#tables
[options="header"]
|===
|Pfad |Parameter |Beschreibung |Rückgabe
| -> Login -> Stellplatzreservierung -> Auswählen eines Campingplatzes -> Maximum Größe änern/Parkplatz auswählen/Maximum Preis auswählen | --- | --- | NullPoiterException 
| -> Login als Boss oder Staff -> Sportgerätemanagement -> Add New/Change Sportitem | Zu großer Input  | wenn man bei Name, Description, Picture, Category oder Amount einen zu langen Input eingibt, kommt der genannte Fehler | Internal Server Error 
| -> Login als Boss oder Staff -> Dauerplätze Management/Platz Management -> hinzufügen | Zu großer Input  | wenn man bei Name, Description oder Picture einen zu langen Input eingibt, kommt der genannte Fehler | Internal Server Error 
|...|...|...|...
|===

== Sonstiges
* Unter Deaktivierung von Javascript gehen einige visuelle Features verloren. Außerdem ist ein Login nicht mehr möglich.
* (Kann möglicherweise an der jar Konvertierung liegen) Viele Übersetzungen sind inkonsistent. Wenn man die Website mit Englisch als Hauptsprache aufruft, sind viele Texte entweder noch auf Deutsch, oder werden als Error (z.B "??catalog.plot.departure_en??")  angezeigt.
* Wenn man bei Homepage versucht, sich mit dem nicht existierenden Konto einzuloggen, wird man zu einer weiteren Login-Seite geführt, wobei keine Fehlermeldung angezeigt wird.
* Fehlende messages.properties:
  ** Fast alles auf englisch/nicht deutsch
	** Auf Deutsch (fehlend):
    *** Titel der Seite Login
    *** Titel der Seite Reservierungen
    *** Plot Size im Dashbord bei Plot Management
    *** Hinzufügen der Sportgeräte beim Sportgerätemanagement: Button und Felder
    *** Beim Hinzufügen von Plätzen sind teilweise Felder auf Englisch, teilweise auf Deutsch
  ** Anmerkungen:
    *** Bei Stellplatzreservierung Arrival/Departure ist bei der deutschen Version auf englisch und fehlt bei der englischen Version
    *** Das gleiche gilt für Dashboard Platz Management bei Picture/Price ...
    *** Übersetzungen sind Inkonsistent
* Nicht ausreichende Überprüfung von Inputs:
  ** Wenn alle Sportequipments eines Typs ausgeliehen sind, kann man trotzdem weitere ausleihen, indem man im HTML den ButtonType von type="button" auf type="submit" setzt.
  ** Wenn man in der Login-Form bei den einzelnen Feldern in HTML required="" löscht, oder den input-Type ändert, kann man invalide Nutzerkonten anlegen.
  ** Bei der Registrierung sind in Feldern Vor- und Nachname die Leerzeichen erlaubt.
  ** Zu langer Input bei den Vor-/Nachname und E-Mail Feldern gibt einen Whitelabel Error Page aus.
  ** Passwort darf, beispielsweise, 12345678 sein(kommt falsche Fehlermeldung: "User with this email already exists!").
  ** /plotcatalog/select : Departure kann vor Arrival-Time sein, wenn Departure zuerst ausgewählt wird
  ** /plotcatalog/select : Min./Max. Preis/Größe kann Negativ sein 
  ** Dashboard:
  *** beim Dauerplätzemanagement sowie beim regulären Platzmanagement ist es beim Editieren möglich, negative Preise und Größen zu setzen
  *** Es ist ebenfalls möglich, bei den Rollen unter Kundenmanagement das disabled im HTML zu entfernen, um somit andere Accounts ebenfalls zum Boss zu machen.

* Fehlende Features:
  ** Gruppenrabatte
  ** Letzten Seasonal Plot nochmals Buchen (Vielleicht wird es im nächsten Jahr angezeigt(?) Dies kann ich aber nicht testen, da Debugging option zur "Zeitreise" fehlt)
  ** Eine Möglichkeit, Seasonal Camping Lots als bezahlt einzustellen: fehlt derzeitig => diese werden in der Accountancy nicht angezeigt (es sei denn, diese gelten als bezahlt wenn der gebuchte Zeitraum um ist - nicht testbar)
  ** Sportgeräte-Buchungen fehlen ebenfalls in der Accountancy (Kaution & Gebühren) sowie bei "meinen Reservierungen".
  ** Kosten für Wartung von Campingplätzen eintragen
* Interaktion mit der Anwendung (Usability):
  ** Warum habt ihr die Legende bei /plotcatalog versteckt? Die ist echt nützlich. Es gab bei uns ein bisschen Verwirrung, was die Farben bedeuten, bis wir die Legende im HTML gefunden haben
  ** Wenn man eine Buchung z.B. im nächsten Jahr abschließen möchte, muss man sich durch alle Wochen durch klicken. Es wäre schön, wenn man automatisch die Woche(n) angezeigt bekommen würde, für die man Arrival/ Departure setzt
  ** Im Darkmode ist die Seite für die Stellplatzreservierung nicht lesbar (wenn ihr einen Darkmode verwenden wollt, sollte das geändert werden)
  ** Es wäre nice, wenn man Reservierungen direkt im Warenkorb löschen könnte
* Logikfehler bei den Sportgeräten
  ** Sportgeräte können von allen Nutzern nachträglich für die Vergangenheit reserviert werden
  ** Reservierungen sind eine Stunde kürzer als sie im Warenkorb angezeigt werden, da die Anfangs- und Endzeit der Reservierung jeweils als Stunde gezählt wird
  -> dementsprechend muss der Kunde bei jeder Ausleihe eine extra Stunde zahlen
  ** die Anzahl der freien Sportgeräte bei den Bildern ist noch implementiert und ist bei den Tischtennisgarnituren und den Volleyballnetzen rechts durch fehlende Überlappung mit anderen Bildern sichtbar
  -> Anzeige dieser Anzahl hat wenig Sinn, da diese nach Tag und Tageszeit variiert

== Verbesserungsvorschläge
* Wäre cool, wenn Seasonal-Buchungen auch im Warenkorb angezeigt würden, damit man evt. Reservierungen Löschen kann, wenn man sich verklickt hat
* Wenn es schon eine Möglichkeit gibt, die Bilder-Urls anzupassen, wäre auch eine Möglichkeit, Bilder hochzuladen, passend
