= Persönliches Feedback eines Teammitgliedes des Softwarepraktikums 2023/24
// Auch wenn der Bogen nicht anonymisiert ist, dürfen Sie gern Ihre Meinung offen kundtun.
// Sowohl positive als auch negative Anmerkungen werden gern gesehen und zur stetigen Verbesserung genutzt.
// Versuchen Sie in dieser Auswertung also stets sowohl Positives wie auch Negatives zu erwähnen.

**Von:**Jannes Mueller

**Gruppe:**06

== Was habe ich gelernt / was habe ich nicht gelernt?
// Ausführung der positiven und negativen Erfahrungen, die im Softwarepraktikum gesammelt wurden
Das gemeinsame Programmieren im Team war eine wertvolle Erfahrung. Mit dem Code von Anderen weiter arbeiten, sich gemeinsam zu organisieren und gegebenenfalls zu unterstützen sowie unterschiedliche Meinungen zu dem Projekt/ der Aufgabenstellung auszudiskutieren gehörten zu den Punkten, welche eine professionelle Softwareentwicklung sehr gut simulierten. Somit hat das SWP einen guten ersten Eindruck in die Praxis (soweit es der Uni möglich war) gegeben.


== Welche Erfahrungen habe ich mit der Zusammenarbeit im Team gemacht?
// Kurze Beschreibung der Zusammenarbeit im Team. Was lief gut? Was war verbesserungswürdig? Was würden Sie das nächste Mal anders machen?
Die Zusammenarbeit im Team funktionierte sehr gut. Die Teammeetings fanden regelmäßig und so gut wie immer auch in voller Anwesenheit statt. Alle Teammitglieder waren zuverlässig und stets hilfsbereit, falls man selber auf eine Frage oder ein Problem gestoßen ist. Das Pair-Programming konnte nicht richtig wie vorgesehen umgesetzt werden, da es hierbei häufiger zu zeitlichen Problemen kam und ein Teammitglied vorzeitig vorher ausgeschieden ist.


== Welche Erfahrungen habe ich bei der Wiederverwendung von Bibliotheken/Frameworks (insbesondere SalesPoint) gemacht?
// Einschätzung der Arbeit mit den bereitgestellten und zusätzlich genutzten Frameworks. Was War gut? Was war verbesserungswürdig?
Durch das Praktikum hat man gute Einblicke mit Bibliotheken/Frameworks bekommen, vor allem wenn vorher noch nicht richtig mit eben diesen gearbeitet hat. Das Salespoint-Framework empfand ich an einigen Stellen etwas schlecht anpassbar und die Dokumentation war teils ebenfalls etwas kurz. 


== Welche Vorschläge zur weiteren Verbesserung des Softwarepraktikums gibt es?
// Möglichst mit Beschreibung, warum die Umsetzung des von Ihnen angebrachten Vorschlages nötig ist.
Da es zum Beginn des Praktikums häufiger zu Problemen bezüglich der Raumauswahl für die Teammeetings kam, denke ich wäre es sinnvoll eine Anzahl an Räumen vor zu halten welche von den Tutoren gebucht werden können. 


== Feedback für den Tutor
// Fühlten Sie sich durch den vom Lehrstuhl bereitgestellten Tutor gut betreut? Was war positiv? Was war verbesserungswürdig?
Der Tutor hat das Projekt gut geleitet. Es wurden alle wichtigen Punkte, Termine und Kriterien gut und rechtzeitig kommuniziert. Auch Fragen zu Problemen oder Bugs im eigenen Code konnten immer sofort beantwortet werden.


== Sonstiges und Anmerkungen
// Welche Aspekte fanden in den oben genannten Punkten keine Erwähnung?
keine Anmerkung
