@startuml
hide empty fields
hide empty methods
skinparam classAttributeIconSize 0
skinparam linetype ortho
skinparam BackgroundColor #FEFEFE
allowmixing
skinparam packageStyle Frame

class campingplatz.utils.DetailedProduct
class campingplatz.reservation.Cart<T extends Product, U extends Reservation<T>>
class campingplatz.reservation.Reservation<T extends Product>
interface campingplatz.reservation.ReservationRepository<T extends Product, U extends Reservation<T>>

package org{
    package salespointframework{
        interface catalog.Catalog<T extends Product>
        class core.DataInitializer
    }
}

package campingplatz.equip {
    package sportItemReservations{
    class SportItemCart{
    }
    class SportItemReservation<<Entity>>{
    +SportItemReservation(UserAccount userAccount, SportItem sportItem, LocalDateTime arrival, LocalDateTime departure)
    +getIntervalUnit(): ChronoUnit
    }
    interface SportItemReservationRepository
    }
    class SportItem<<Entity>>{
    -amount: int
    -deposit: Money
    +SportItem(String name, Money rentalFee, Money deposit, String category, int amount, String imagePath, String description)
    +getAmount(): int
    +setAmount(int value): void
    +getDeposit(): Money
    +setDeposit(Money value): void
    }
    interface SportItemCatalog{
    +findById(Product.ProductIdentifier id): Optional<SportItem>
    }
    class SportItemCatalogController<<Controller>>{
    -itemCatalog: SportItemCatalog
    +SportItemCatalogController(SportItemCatalog itemCatalog)
    +setupCatalog(Model model, Optional<UserAccount> user): String
    +setup(Model model): String
    +showSportItemDetails(Product.ProductIdentifier id, Model model): String
    +addSportItem(String name, double price, double deposit, int amount, String category, String imagePath,	String desc): String
    +changeSportItemAmount(int amountItem, Product.ProductIdentifier equip_id): String
    +deleteSportItem(String itemName, Product.ProductIdentifier id): String
    }
    class SportItemCatalogDataInitializer<<Component>>{
    -sportItemCatalog: SportItemCatalog
    +SportItemCatalogDataInitializer(SportItemCatalog sportItemCatalog)
    +initialize(): void
    }

}

SportItem -r|> DetailedProduct
SportItem -[hidden]u- SportItemCatalogDataInitializer
SportItemCatalog --|> Catalog: <<bind T->SportItem>>
SportItemCatalogController -[hidden]u- SportItem


SportItemCatalogDataInitializer --|> DataInitializer

campingplatz -[hidden]l- org

SportItemCatalogController ..> SportItemCatalog: <<use>>

SportItemCart --|> Cart: <<bind T->SportItem, U->SportItemReservation>>
SportItemReservation --|> Reservation
SportItemReservationRepository --|> ReservationRepository: <<bind T->SportItem, U->SportItemReservation>>

Cart -[hidden]d- Reservation
Reservation -[hidden]u- ReservationRepository

SportItemCart -[hidden]d- SportItemReservation
SportItemReservation -[hidden]u- SportItemReservationRepository

@enduml