@startuml
hide empty fields
hide empty methods
skinparam classAttributeIconSize 0
skinparam linetype ortho
skinparam BackgroundColor #FEFEFE
allowmixing
skinparam packageStyle Frame

interface campingplatz.utils.Priced
class campingplatz.reservation.Cart


package org{
    package salespointframework{
    class DataInitializer{}
    }
    package springframework{
    interface data.repository.CrudRepository<T, ID>
    }
}

package campingplatz.reservation{

    class Reservation<T extends Product>{
    +id: UUID
    -user: UserAccount
    -product: T
    -begin: LocalDateTime
    -end: LocalDateTime
    +Reservation(UserAccount user, T product, LocalDateTime begin, LocalDateTime end)
    +getPrice(): MonetaryAmount
    +getIntervalUnit(): ChronoUnit
    +duration(): long
    +getId(): UUID
    +getUser(): UserAccount
    +setUser(UserAccount value): void
    +getProduct(): T
    +setProduct(T value): void
    +getBegin(): LocalDateTime
    +setBegin(LocalDateTime value): void
    +getEnd(): LocalDateTime
    +setEnd(LocalDateTime value): void
    }
    class ReservationController{
    -reservationRepository: ReservationRepository<Plot>
    +initializeCart(): Cart<Plot>
    +cart(Model model, UserAccount userAccount, Cart<Plot> reservationCart): String
    +reservate(Model model, UserAccount userAccount, Cart<Plot> reservationCart): String
    +orders(Model model, UserAccount user): String
    }
    class ReservationDataInitializer{
    -reservationRepository: ReservationRepository<Plot>
    -customerManagement: CustomerManagement
    -plotCatalog: PlotCatalog
    +ReservationDataInitializer(ReservationRepository<Plot> reservationRepository, CustomerManagement customerManagement, PlotCatalog plotCatalog)
    +initialize(): void
    }
    class ReservationEntry<T extends Product>{
    -product: T
    -time: LocalDateTime
    +ReservationEntry(T product, LocalDateTime time)
    +compareTo(ReservationEntry<T> second): int
    +getProduct(): T
    +setProduct(T value): void
    +getTime(): LocalDateTime
    +setTime(LocalDateTime value): void
    }
    interface ReservationRepository<U extends Product>{
    +findAll(): List<Reservation<U>>
    +findByUserId(UserAccount.UserAccountIdentifier id): List<Reservation<U>>
    +findReservationsBetween(LocalDateTime arrival, LocalDateTime departure): List<Reservation<U>>
    +findPlotsReservedBetween(LocalDateTime arrival, LocalDateTime departure): Set<U>
    +productIsReservedIn(U product, LocalDateTime arrival, LocalDateTime departure): Boolean
    +productIsAvailableIn(U product, LocalDateTime arrival, LocalDateTime departure): Boolean
    }
    class SportItemReservation{
    +SportItemReservation(UserAccount userAccount, SportItem sportItem, LocalDateTime arrival, LocalDateTime departure)
    +getIntervalUnit(): ChronoUnit
    }
}
Reservation ..|> Priced

ReservationController ..> ReservationRepository: <<bind U->Plot>>
ReservationController ..> Cart: <<bind T->Plot>>

ReservationDataInitializer ..|> DataInitializer

ReservationRepository ..|> CrudRepository

@enduml