@startuml
hide empty fields
hide empty methods
skinparam classAttributeIconSize 0
skinparam linetype ortho
skinparam BackgroundColor #FEFEFE
allowmixing
skinparam packageStyle Frame

package campingplatz{
class Campingplatz{
+main(String args): void
}
class WebSecurityConfiguration {
+CampingPlatzSecurity(HttpSecurity http): SecurityFilterChain
}

}

WebSecurityConfiguration -u-+ Campingplatz
@enduml